version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./api/src:/app/src
      - ./tsconfig.json:/tsconfig.json
    environment:
      - PORT=3001
      - SECRET_KEY
      - EMAIL_SERVICE
      - FROM_EMAIL
      - FROM_EMAIL_PASSWORD
      - TO_EMAIL

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client/public:/app/public
      - ./client/src:/app/src
      - ./tsconfig.json:/tsconfig.json

  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
