version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client/public:/app/public
      - ./client/src:/app/src
    ports:
      - 3000:3000

  nginx:
    depends_on:
      - client
      # - api
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
