version: "3.9"

services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - ./api/src:/app/api
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - PORT=3001
  #     - SECRET_KEY

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      # - /app/node_modules
      - ./client/public:/app/public
      - ./client/src:/app/src
    ports:
      - 3000:3000

  nginx:
    depends_on:
      - client
      # - api
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
